version: '3'
services:
  realize:
    build: .
    tty: true
    volumes:
      - .:/go/src/github.com/YanaPIIDXer/QiitaLineBot
    ports:
      - "3000:3000"
    command: realize start --name='server' --run
    restart: always
